# Generated by Django 4.1.6 on 2023-02-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
