# Generated by Django 4.1.6 on 2023-02-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_project_additional_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='additional_notes',
        ),
    ]
